<?php

/**
* Display help and module information.
* @param path
*   Which path of the site we're displaying help.
* @param arg
*   Array that holds the current path as would be returned from arg() function.
* @return
*   help text for the path.
*/
function pp_admin_menu_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#pp_admin_menu":
      $output = '<p>'. t("Sortiert alle Einstellungen der Piraten Drupal Module in ein Submenu ein.").'</p>';
      break;
  }
  return $output;
} // function pp_admin_menu_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the pp_admin_menu module
*/

function pp_admin_menu_perm() {
  return array('administer pp_admin_menu');
} // function pp_admin_menu_perm()


/**
 * Implementation of hook_menu()
 */
function pp_admin_menu_menu() {
  $items = array();

  $items['admin/settings/piraten'] = array(
    'title' => 'Piratenpartei',
    'description' => 'Liste aller Einstellung der Piraten Drupal Module.',
#    'page callback' => 'drupal_get_form',
#    'page arguments' => array('pp_admin_menu_admin_form'),
    'access arguments' => array('administer pp_admin_menu'),
#    'file' => 'pp_admin_menu.admin.inc',
    'type' => MENU_NORMAL_ITEM,

    'page callback' => 'system_admin_menu_block_page',
 #   'access callback' => 'simplenews_newsletter_access',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),


  );

  return $items;
}

?>
